# Entropy calculation for Crop Yield

In [1]:
#import library packages
import pandas as p
import matplotlib.pyplot as plt
import seaborn as s
import numpy as n
#read the given dataset
df = p.read_csv("df.csv")
df.rename(columns={'Mean Temp':'T'}, inplace=True)
df.rename(columns={'Average Humidity':'H'}, inplace=True)
df.rename(columns={'rainfall':'R'}, inplace=True)
df.rename(columns={'Cost of Cultivation (`/Hectare) C2':'CC'}, inplace=True)
df.rename(columns={'Cost of Production (`/Quintal) C2':'CP'}, inplace=True)
df.rename(columns={'Yield (Quintal/ Hectare) ':'Y'}, inplace=True)
df.rename(columns={'cost of production per yield':'CPPY'}, inplace=True)
from sklearn.preprocessing import LabelEncoder
var_mod = ['Y']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(str)
df['YPr']= df.Y.map({'13':0, '7':0, '11':0, '4':0, '23':0, '39':1, '10':0, '18':0, '36':1, '47':1, '8':0, '3':0,
       '38':1, '46':1, '5':0, '9':0, '2':0, '44':1, '17':0, '41':1, '6':0, '16':0, '35':1, '19':0,
       '0':0, '43':1, '12':0, '45':1, '25':0, '33':1, '29':0, '37':1, '32':1, '21':0, '42':1,
       '48':1, '30':1, '34':1, '26':0, '20':0, '31':1, '24':0, '27':0, '22':0, '40':1, '28':0,
       '1':0, '14':0, '15':0})

from sklearn.preprocessing import LabelEncoder
var_mod = ['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Crop', 'Area',
       'R', 'H', 'T', 'CC', 'CP', 'Y','CPPY']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(str)
df.head()

State_Name District_Name Crop_Year Season Crop  Area    R   H   T  CC  CP  \
0          0           410         3      1    2  2025   33  45  10  21  30   
1          0           410         4      1    2  2025  121  44   6   3  26   
2          0           410         5      4    2  2030  118  46   1  33  45   
3          0           410         6      4    2  2033  172  45   6   4  36   
4          0           410         7      4    2  2037   75  51  15  20  24   

    Y CPPY  YPr  
0   5  126    0  
1  46   72    0  
2   3  200    0  
3  34   78    0  
4  16  144    0

In [2]:
# Importing the required packages 
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

In [3]:
# Function importing Dataset 
def importdata(): 
    balance_data = df
      
    # Printing the dataswet shape 
    print ("Dataset Lenght: ", len(balance_data)) 
    print('')
    print ("Dataset Shape: ", balance_data.shape) 
      
    
    return balance_data 


In [4]:
# Function to split the dataset 
def splitdataset(balance_data): 
  
    # Seperating the target variable 
    X = balance_data.values[:, 1:5] 
    Y = balance_data.values[:, 0] 
  
    # Spliting the dataset into train and test 
    X_train, X_test, y_train, y_test = train_test_split(  
    X, Y, test_size = 0.3, random_state = 100) 
      
    return X, Y, X_train, X_test, y_train, y_test 


RF

In [5]:
# Function to perform training with entropy. 
def tarin_using_entropyrf(X_train, X_test, y_train): 
  
   
    clf_entropy = RandomForestClassifier( 
            criterion = "entropy", random_state = 100, 
            max_depth = 3, min_samples_leaf = 5) 
  
    # Performing training 
    clf_entropy.fit(X_train, y_train) 
    return clf_entropy 


DT

In [6]:
# Function to perform training with entropy. 
def tarin_using_entropydt(X_train, X_test, y_train): 
  
   
    clf_entropy = DecisionTreeClassifier( 
            criterion = "entropy", random_state = 100, 
            max_depth = 3, min_samples_leaf = 5) 
  
    # Performing training 
    clf_entropy.fit(X_train, y_train) 
    return clf_entropy 


Process

In [7]:
  
# Function to make predictions 
def prediction(X_test, clf_object): 
  
    # Predicton on test with giniIndex 
    y_pred = clf_object.predict(X_test) 
    print("Predicted values:") 
    print('')
    print(y_pred) 
    return y_pred 


Random Forest Entropy Result

In [8]:
# Function to calculate accuracy 
def cal_accuracy(y_test, y_pred): 
    print('') 
    print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred)) 
    print('') 
   
    print('')
    print('')
    print("Report : ", 
    classification_report(y_test, y_pred)) 
  
# Driver code 
def main(): 
      
    # Building Phase 
    data = importdata() 
    X, Y, X_train, X_test, y_train, y_test = splitdataset(data) 
   
    clf_entropy = tarin_using_entropyrf(X_train, X_test, y_train) 
    print('') 
   
    print('')
    print("Results Using Entropy of Random Forest:") 
    # Prediction using entropy 
    y_pred_entropy = prediction(X_test, clf_entropy) 
    cal_accuracy(y_test, y_pred_entropy) 
      
      # Calling main function 
if __name__=="__main__": 
    main() 

Dataset Lenght:  233864

Dataset Shape:  (233864, 14)


Results Using Entropy of Random Forest:
Predicted values:

['16' '30' '30' ... '22' '30' '30']

Confusion Matrix: 
 [[  0   0   0 ...   0   0   0]
 [  0 377   0 ...   0   0   0]
 [  0  68   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]



Report :               precision    recall  f1-score   support

          0       0.00      0.00      0.00        64
          1       0.30      0.13      0.18      2913
         10       0.00      0.00      0.00      1759
         11       0.00      0.00      0.00       749
         12       0.00      0.00      0.00       486
         13       0.00      0.00      0.00       361
         14       0.29      0.05      0.09      6214
         15       0.40      0.00      0.01      1275
         16       0.17      0.29      0.22      6928
         17       1.00      0.00      0.00      3819
         18       0.00      0.00      0

C:\Users\lavan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Decision Tree Entropy Result

In [9]:
# Function to calculate accuracy 
def cal_accuracy(y_test, y_pred): 
    print('') 
    print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred)) 
    print('') 
   
    print('')
    print('')
    print("Report : ", 
    classification_report(y_test, y_pred)) 
  
# Driver code 
def main(): 
      
    # Building Phase 
    data = importdata() 
    X, Y, X_train, X_test, y_train, y_test = splitdataset(data) 
   
    clf_entropy = tarin_using_entropydt(X_train, X_test, y_train) 
    print('') 
   
    print('')
    print("Results Using Entropy of Decision Tree:") 
    # Prediction using entropy 
    y_pred_entropy = prediction(X_test, clf_entropy) 
    cal_accuracy(y_test, y_pred_entropy) 
      
      # Calling main function 
if __name__=="__main__": 
    main() 

Dataset Lenght:  233864

Dataset Shape:  (233864, 14)


Results Using Entropy of Decision Tree:
Predicted values:

['16' '30' '30' ... '30' '30' '30']

Confusion Matrix: 
 [[  0   0   0 ...   0   0   0]
 [  0 527   0 ...   0   0   0]
 [  0  74   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]



Report :               precision    recall  f1-score   support

          0       0.00      0.00      0.00        64
          1       0.30      0.18      0.23      2913
         10       0.00      0.00      0.00      1759
         11       0.00      0.00      0.00       749
         12       0.00      0.00      0.00       486
         13       0.00      0.00      0.00       361
         14       0.00      0.00      0.00      6214
         15       0.00      0.00      0.00      1275
         16       0.16      0.31      0.21      6928
         17       0.00      0.00      0.00      3819
         18       0.00      0.00      0

C:\Users\lavan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
